version: '3.3'
services:
   db:
     image: mysql
     volumes:
       - db_vol:/var/lib/mysql
       - ./mysql-dump:/docker-entrypoint-initdb.d
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: proyectodam
       MYSQL_USER: testuser
       MYSQL_PASSWORD: root
     ports:
       - 3306:3306
   phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
   web:
    build:
      context: .       
    depends_on:
      - db
    image: tomcat
    volumes:
            - ./target/demo.war:/usr/local/tomcat/webapps/demo.war
    ports:
      - '7070:8080'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: proyectodam
      MYSQL_USER: testuser
      MYSQL_PASSWORD: root
volumes:
    db_vol:   